spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
