spring:
  datasource:
    url: jdbc:mariadb://localhost:8070/member
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
